apiVersion: v1
kind: ServiceAccount
metadata:
  name: tail-lifter
  namespace: tailscale-relay
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tail-lifter
rules:
- apiGroups: [""]
  resources: ["endpoints", "services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tail-lifter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tail-lifter
subjects:
- kind: ServiceAccount
  name: tail-lifter
  namespace: tailscale-relay